<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.10.1 setup script
 * Date: Tue, 06 Mar 2012 16:17:22 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
/*$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
/*$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
/*$cfg['Servers'][$i]['auth_type'] = 'cookie';
/*$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'BBs&3440';
$cfg['DefaultLang'] = 'en';
/*$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>